/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorProveedores;
import Modelo.Proveedor;
import Modelo.Servicio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VtnAgrega_oModificaProveedor extends javax.swing.JFrame {

    private static VtnAgrega_oModificaProveedor instanciaVtnAgregaoModificaProveedor = new VtnAgrega_oModificaProveedor();

    private boolean seModificaraProveedor;
    private Proveedor proveedorDeLaTabla;

    /**
     * Creates new form VtnAgrega_oModificaProveedor
     */
    public VtnAgrega_oModificaProveedor() {
        initComponents();
        //colocamos la ventana en el centro.
        setLocationRelativeTo(null);
        seModificaraProveedor = false;
        inicializarCamposDeEvento();
    }

    public static VtnAgrega_oModificaProveedor getInstanciaVtnAgregaoModificaProveedor() {
        return instanciaVtnAgregaoModificaProveedor;
    }

    public void setProveedorDeLaTabla(Proveedor proveedorDeLaTabla) {
        this.proveedorDeLaTabla = proveedorDeLaTabla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarProveedor = new javax.swing.JButton();
        txtDireccionProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        btnRegresarVtnProveedores = new javax.swing.JButton();
        Correo = new javax.swing.JLabel();
        Dirección = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloProveedor = new javax.swing.JLabel();
        cbCarpaEvento = new javax.swing.JCheckBox();
        cbBanqueteraEvento = new javax.swing.JCheckBox();
        cbLucesEvento = new javax.swing.JCheckBox();
        cbLugarEvento = new javax.swing.JCheckBox();
        cbMusicaEvento = new javax.swing.JCheckBox();
        txtBanqueteraEvento = new javax.swing.JTextField();
        txtCarpaEvento = new javax.swing.JTextField();
        txtLucesEvento = new javax.swing.JTextField();
        txtLugarEvento = new javax.swing.JTextField();
        txtMusicaEvento = new javax.swing.JTextField();
        lblSeleccionar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Proveedor");

        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });

        btnRegresarVtnProveedores.setText("Regresar");
        btnRegresarVtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnProveedoresActionPerformed(evt);
            }
        });

        Correo.setText("Correo:");

        Dirección.setText("Dirección:");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Teléfono:");

        tituloProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloProveedor.setText("Proveedor");

        cbCarpaEvento.setText("Carpa");
        cbCarpaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarpaEventoActionPerformed(evt);
            }
        });

        cbBanqueteraEvento.setText("Banquetera");
        cbBanqueteraEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanqueteraEventoActionPerformed(evt);
            }
        });

        cbLucesEvento.setText("Luces");
        cbLucesEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLucesEventoActionPerformed(evt);
            }
        });

        cbLugarEvento.setText("Lugar");
        cbLugarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLugarEventoActionPerformed(evt);
            }
        });

        cbMusicaEvento.setText("Música");
        cbMusicaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMusicaEventoActionPerformed(evt);
            }
        });

        txtBanqueteraEvento.setEditable(false);

        txtCarpaEvento.setEditable(false);

        txtLucesEvento.setEditable(false);

        txtLugarEvento.setEditable(false);

        txtMusicaEvento.setEditable(false);

        lblSeleccionar.setText("Seleccione los servicios del proveedor y establezca sus costos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarProveedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegresarVtnProveedores)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tituloProveedor)
                                .addGap(242, 242, 242))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(Dirección))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreProveedor)
                            .addComponent(txtTelefonoProveedor)
                            .addComponent(txtDireccionProveedor)
                            .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addComponent(Correo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(cbBanqueteraEvento)
                        .addGap(6, 6, 6)
                        .addComponent(txtBanqueteraEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbCarpaEvento)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(cbLucesEvento)
                        .addGap(6, 6, 6)
                        .addComponent(txtLucesEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMusicaEvento)
                        .addGap(18, 18, 18)
                        .addComponent(txtMusicaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCarpaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(cbLugarEvento)
                        .addGap(18, 18, 18)
                        .addComponent(txtLugarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tituloProveedor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dirección)
                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCarpaEvento)
                        .addComponent(txtCarpaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbBanqueteraEvento)
                        .addComponent(cbLugarEvento)
                        .addComponent(txtBanqueteraEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLugarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLucesEvento)
                    .addComponent(cbMusicaEvento)
                    .addComponent(txtLucesEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMusicaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor)
                    .addComponent(btnRegresarVtnProveedores))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void cbCarpaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarpaEventoActionPerformed
        if (this.cbCarpaEvento.isSelected()) {
            this.txtCarpaEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbCarpaEventoActionPerformed

    private void cbMusicaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusicaEventoActionPerformed
        if (this.cbMusicaEvento.isSelected()) {
            this.txtMusicaEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbMusicaEventoActionPerformed

    private void txtBanqueteraEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanqueteraEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanqueteraEventoActionPerformed

    private void cbBanqueteraEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanqueteraEventoActionPerformed
        if (this.cbBanqueteraEvento.isSelected()) {
            this.txtBanqueteraEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbBanqueteraEventoActionPerformed

    private void txtLucesEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucesEventoActionPerformed

    }//GEN-LAST:event_txtLucesEventoActionPerformed

    private void txtLugarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarEventoActionPerformed

    }//GEN-LAST:event_txtLugarEventoActionPerformed

    private void txtMusicaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMusicaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMusicaEventoActionPerformed

    private void inicializarCamposDeEvento() {
        this.txtBanqueteraEvento.setEditable(false);
        this.txtCarpaEvento.setEditable(false);
        this.txtLucesEvento.setEditable(false);
        this.txtMusicaEvento.setEditable(false);
        this.txtLugarEvento.setEditable(false);
    }


    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        
        LinkedList<Servicio> servicios = obtenerServicioSeleccionados();

        String nombre = this.txtNombreProveedor.getText();
        String direccion = this.txtDireccionProveedor.getText();
        String telefono = this.txtTelefonoProveedor.getText();
        String correo = this.txtCorreoProveedor.getText();

        Proveedor tempProveedor = new Proveedor(0, nombre, direccion, telefono, correo);
        tempProveedor.setServiciosQueProvee(servicios);
        
        ControladorProveedores ctrlProveedor = new ControladorProveedores();

        try {

            if (!seModificaraProveedor) {
                boolean seAgregoProveedor = ctrlProveedor.agregar(tempProveedor);
                if (seAgregoProveedor) {
                    mostrarMensajeEnPantalla("Proveedor Agregado");
                } else {
                    mostrarMensajeEnPantalla("Proveedor No Agregado");
                }

            } else {
                tempProveedor.setIdPersona(proveedorDeLaTabla.getIdPersona());
                boolean seModificoProveedor = ctrlProveedor.modificar(tempProveedor);
                if (seModificoProveedor) {
                    mostrarMensajeEnPantalla("Proveedor Modificado");
                } else {
                    mostrarMensajeEnPantalla("Proveedor No Modificado");
                }
                //lo devolvemos a su estado de inicio.
                seModificaraProveedor = false;

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
           // mostrarMensajeEnPantalla("Hubo un error con la "
             //       + "base de datos. *******Fue en agregar Proveedor*****" + ex.getLocalizedMessage());

        }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private LinkedList<Servicio> obtenerServicioSeleccionados() {
        LinkedList<Servicio> servicios = new LinkedList<>();

        float precioServicio = 0;

        if (this.cbBanqueteraEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtBanqueteraEvento.getText());
            servicios.add(new Servicio("Banquetera", precioServicio));
        }
        if (this.cbCarpaEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtCarpaEvento.getText());
            servicios.add(new Servicio("Carpa", precioServicio));

        }
        if (this.cbLucesEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtLucesEvento.getText());
            servicios.add(new Servicio("Iluminacion", precioServicio));

        }
        if (this.cbLugarEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtLugarEvento.getText());
            servicios.add(new Servicio("Lugar", precioServicio));

        }
        if (this.cbMusicaEvento.isSelected()) {
            precioServicio = Float.parseFloat(this.txtMusicaEvento.getText());
            servicios.add(new Servicio("Musica", precioServicio));
        }
        return servicios;
    }


    private void btnRegresarVtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnProveedoresActionPerformed
        VtnProveedores vtnRegreso = VtnProveedores.getInstanciaDeVtnProveedores();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();

    }//GEN-LAST:event_btnRegresarVtnProveedoresActionPerformed

    private void cbLucesEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLucesEventoActionPerformed
        if (this.cbLucesEvento.isSelected()) {
            this.txtLucesEvento.setEditable(true);
        } else {
            this.txtLucesEvento.setText("");
            this.txtLucesEvento.setEditable(false);
        }
    }//GEN-LAST:event_cbLucesEventoActionPerformed

    private void cbLugarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLugarEventoActionPerformed
        if (this.cbLugarEvento.isSelected()) {
            this.txtLugarEvento.setEditable(true);
        } else {
            this.txtLugarEvento.setText("");
            this.txtLugarEvento.setEditable(false);
        }
    }//GEN-LAST:event_cbLugarEventoActionPerformed

    private void mostrarMensajeEnPantalla(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Cuidado", 0);
    }

    private void borraDatosDeCampos() {
        this.txtCorreoProveedor.setText("");
        this.txtDireccionProveedor.setText("");
        this.txtNombreProveedor.setText("");
        this.txtTelefonoProveedor.setText("");
        this.txtBanqueteraEvento.setText("");
        this.txtCarpaEvento.setText("");
        this.txtLucesEvento.setText("");
        this.txtLugarEvento.setText("");
        this.txtMusicaEvento.setText("");
        this.cbBanqueteraEvento.setSelected(false);
        this.cbCarpaEvento.setSelected(false);
        this.cbLucesEvento.setSelected(false);
        this.cbLugarEvento.setSelected(false);
        this.cbMusicaEvento.setSelected(false);
    }

    private void cerrarEstaVentana() {
        borraDatosDeCampos();
        this.dispose();
    }

    public javax.swing.JTextField getTxtCorreoProveedor() {
        return txtCorreoProveedor;
    }

    /**
     * @return the txtDireccionCliente
     */
    public javax.swing.JTextField getTxtDireccionProveedor() {
        return txtDireccionProveedor;
    }

    /**
     * @return the txtNombreCliente
     */
    public javax.swing.JTextField getTxtNombreProveedor() {
        return txtNombreProveedor;
    }

    /**
     * @return the txtTelefonoCliente
     */
    public javax.swing.JTextField getTxtTelefonoProveedor() {
        return txtTelefonoProveedor;
    }

    public javax.swing.JTextField getTxtBanqueterEvento() {
        return txtBanqueteraEvento;
    }

    public javax.swing.JTextField getTxtCarpaEvento() {
        return txtCarpaEvento;
    }

    public javax.swing.JTextField getTxtLucesEvento() {
        return txtLucesEvento;
    }

    public javax.swing.JTextField getTxtLugarEvento() {
        return txtLugarEvento;
    }

    public javax.swing.JTextField getTxtMusicaEvento() {
        return txtMusicaEvento;
    }

    public JCheckBox getCbCarpaEvento() {
        return cbCarpaEvento;
    }

    public JCheckBox getCbLucesEvento() {
        return cbLucesEvento;
    }

    public JCheckBox getCbBanqueteraEvento() {
        return cbBanqueteraEvento;
    }

    public JCheckBox getCbLugarEvento() {
        return cbLugarEvento;
    }

    public JCheckBox getCbMusicaEvento() {
        return cbMusicaEvento;
    }

    /**
     * @return the seModificaraCliente
     */
    public boolean isSeModificaraProveedor() {
        return seModificaraProveedor;
    }

    /**
     * @param seModificaraCliente the seModificaraCliente to set
     */
    public void setSeModificaraProveedor(boolean seModificaraProveedor) {
        this.seModificaraProveedor = seModificaraProveedor;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgrega_oModificaProveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Dirección;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnRegresarVtnProveedores;
    private javax.swing.JCheckBox cbBanqueteraEvento;
    private javax.swing.JCheckBox cbCarpaEvento;
    private javax.swing.JCheckBox cbLucesEvento;
    private javax.swing.JCheckBox cbLugarEvento;
    private javax.swing.JCheckBox cbMusicaEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JLabel tituloProveedor;
    private javax.swing.JTextField txtBanqueteraEvento;
    private javax.swing.JTextField txtCarpaEvento;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtLucesEvento;
    private javax.swing.JTextField txtLugarEvento;
    private javax.swing.JTextField txtMusicaEvento;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables
}
